# Generated by Django 4.1.7 on 2023-03-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
