# Generated by Django 4.1.7 on 2023-03-05 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_account_giftcard_delete_netflixgiftcard_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="giftcard",
            old_name="activation_date",
            new_name="date",
        ),
    ]
