version: "3.1"

services:
  db:
    restart: always
    image: postgres
    container_name: shareflix-postgres
    environment:
      - POSTGRES_USER=shareflix
      - POSTGRES_PASSWORD=shareflix123
      - POSTGRES_DB=shareflix
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  shareflix:
    image: shareflix
    build:
      #TODO: move shareflix stuff to dedicated directory
      context: .
      dockerfile: Dockerfile
    container_name: shareflix
    depends_on:
      - db
    environment:
      - PGPASSWORD=shareflix123
      - PGUSER=shareflix
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=shareflix
    ports:
      - "5051:8000"
    restart: always


volumes:
  postgres_data:

