# Generated by Django 3.1.3 on 2020-11-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialclaim',
            name='status',
            field=models.CharField(choices=[('OP', 'open'), ('PD', 'paid')], default='OP', max_length=2),
        ),
    ]
