# Generated by Django 3.1.3 on 2020-11-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareflix', '0002_auto_20201119_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialclaim',
            options={'permissions': (('can_add_financial_claim', 'Can add cost price'),)},
        ),
    ]
