# Generated by Django 4.0 on 2021-12-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareflix', '0003_auto_20201120_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netflixgiftcard',
            old_name='amount',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='netflixaccount',
            name='billing_date',
        ),
        migrations.RemoveField(
            model_name='netflixaccount',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='netflixaccount',
            name='monthly_costs',
        ),
        migrations.RemoveField(
            model_name='netflixgiftcard',
            name='currency',
        ),
        migrations.AddField(
            model_name='netflixgiftcard',
            name='redem_worth_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
